services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app:consistent
    env_file:
      - .env
    command: streamlit run /app/src/dashboard.py

  flask-app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app:consistent
      - ./data:/data:consistent
    env_file:
      - .env
    command: python /app/src/app.py
    working_dir: /app
