services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app/
    environment:
      - TZ=America/Los_Angeles
      - DEBIAN_FRONTEND=noninteractive
      - API_KEY=
      - LABEL=